-- ============================================================
--  Lyzoo Group — Inventory & COGS
--  shipments.sql  ·  run ONCE in Supabase → SQL Editor
--  Adds the Shipments feature. Additive & non-destructive.
-- ============================================================

create table if not exists shipments (
  id            bigint generated by default as identity primary key,
  shipment_no   text not null,
  po_numbers    text[] default '{}',      -- linked purchase-order numbers
  carrier       text,                     -- DHL / FedEx / UPS / DPD / Royal Mail / Evri / …
  tracking_numbers text[] default '{}',   -- one or more tracking numbers
  cartons       integer default 0,
  total_kg      numeric default 0,
  comments      text,
  expected_date date,
  shipment_date date,
  received      boolean default false,   -- true once goods physically arrive
  received_date date,
  created_at    timestamptz default now()
);

alter table shipments enable row level security;

drop policy if exists "auth read"  on shipments;
drop policy if exists "auth write" on shipments;

create policy "auth read"  on shipments for select
  using (auth.role() = 'authenticated');
create policy "auth write" on shipments for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- If the shipments table already exists, add the new columns instead:
--   alter table shipments add column if not exists carrier text;
--   alter table shipments add column if not exists tracking_numbers text[] default '{}';
--   alter table shipments add column if not exists received boolean default false;
--   alter table shipments add column if not exists received_date date;
